# Generated by Django 2.2.13 on 2020-06-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=32, verbose_name='game_name')),
                ('max_players', models.IntegerField(default=4, verbose_name='max_players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatanGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatanCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(db_index=True, verbose_name='x')),
                ('y', models.IntegerField(db_index=True, verbose_name='y')),
                ('stackable', models.BooleanField(db_index=True, default=True, verbose_name='stackable')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='room.CatanGrid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=32, verbose_name='game_name')),
                ('max_players', models.IntegerField(default=2, verbose_name='max_players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(db_index=True, verbose_name='x')),
                ('y', models.IntegerField(db_index=True, verbose_name='y')),
                ('stackable', models.BooleanField(db_index=True, default=False, verbose_name='stackable')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='room.ChessGrid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isWhite', models.BooleanField(db_index=True, verbose_name='isWhite')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure', to='room.ChessCell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=32, verbose_name='nickname')),
                ('is_host', models.BooleanField(db_index=True, default=False, verbose_name='is_host')),
                ('is_spectator', models.BooleanField(db_index=True, default=False, verbose_name='is_spectator')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Bishop',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='King',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='Knight',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='Rook',
            fields=[
                ('chessitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.ChessItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('room.chessitem',),
        ),
        migrations.CreateModel(
            name='CatanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='room.CatanCell')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
