# Generated by Django 2.2.13 on 2020-06-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=32, verbose_name='game_name')),
                ('max_players', models.IntegerField(default=4, verbose_name='max_players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatanCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(db_index=True, verbose_name='x')),
                ('y', models.IntegerField(db_index=True, verbose_name='y')),
                ('stackable', models.BooleanField(db_index=True, default=True, verbose_name='stackable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatanGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=32, verbose_name='game_name')),
                ('max_players', models.IntegerField(default=2, verbose_name='max_players')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(db_index=True, verbose_name='x')),
                ('y', models.IntegerField(db_index=True, verbose_name='y')),
                ('stackable', models.BooleanField(db_index=True, default=False, verbose_name='stackable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=32, verbose_name='nickname')),
                ('is_host', models.BooleanField(db_index=True, default=False, verbose_name='is_host')),
                ('is_spectator', models.BooleanField(db_index=True, default=False, verbose_name='is_spectator')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ChessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64, verbose_name='type')),
                ('isWhite', models.BooleanField(db_index=True, verbose_name='isWhite')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_item', to='room.ChessCell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chesscell',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='room.ChessGrid'),
        ),
        migrations.CreateModel(
            name='CatanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64, verbose_name='type')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catan_item', to='room.CatanCell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='catancell',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='room.CatanGrid'),
        ),
    ]
