# Generated by Django 3.0.7 on 2020-06-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catan',
            name='room',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='catan_game', to='room.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chess',
            name='room',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chess_game', to='room.Room'),
            preserve_default=False,
        ),
    ]
