# Generated by Django 3.0.7 on 2020-06-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20200625_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catanitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/catan/'),
        ),
        migrations.AlterField(
            model_name='chessitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chess/'),
        ),
    ]
