# Generated by Django 3.0.7 on 2020-06-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200625_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catan',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='chess',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_spectator',
        ),
        migrations.AlterField(
            model_name='chessitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chess/%d/%m/%Y'),
        ),
    ]
