# Generated by Django 3.0.7 on 2020-06-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200625_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catan',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='chess',
            old_name='room_id',
            new_name='room',
        ),
    ]
