# Generated by Django 2.2 on 2020-06-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20200625_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='catangrid',
            name='cells_type',
            field=models.CharField(blank=True, db_index=True, default='hexagonal', max_length=16, verbose_name='cells_type'),
        ),
        migrations.AddField(
            model_name='catangrid',
            name='size_x',
            field=models.IntegerField(db_index=True, default=0, verbose_name='size_x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catangrid',
            name='size_y',
            field=models.IntegerField(db_index=True, default=0, verbose_name='size_y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='cells_type',
            field=models.CharField(blank=True, db_index=True, default='tetragonal', max_length=16, verbose_name='cells_type'),
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='size_x',
            field=models.IntegerField(blank=True, db_index=True, default=8, verbose_name='size_x'),
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='size_y',
            field=models.IntegerField(blank=True, db_index=True, default=8, verbose_name='size_y'),
        ),
    ]
