# Generated by Django 3.0.7 on 2020-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20200625_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='catangrid',
            name='cells_type',
            field=models.CharField(blank=True, db_index=True, default='hexagonal', max_length=16, verbose_name='cells_type'),
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='cells_type',
            field=models.CharField(blank=True, db_index=True, default='tetragonal', max_length=16, verbose_name='cells_type'),
        ),
    ]
