# Generated by Django 3.0.7 on 2020-06-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20200626_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catangrid',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='catan_grid', to='room.Catan'),
        ),
        migrations.AlterField(
            model_name='chessgrid',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='chess_grid', to='room.Chess'),
        ),
    ]
