# Generated by Django 3.0.7 on 2020-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20200626_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='catangrid',
            name='size_x',
            field=models.IntegerField(db_index=True, default=10, verbose_name='size_x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catangrid',
            name='size_y',
            field=models.IntegerField(db_index=True, default=10, verbose_name='size_y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='size_x',
            field=models.IntegerField(blank=True, db_index=True, default=8, verbose_name='size_x'),
        ),
        migrations.AddField(
            model_name='chessgrid',
            name='size_y',
            field=models.IntegerField(blank=True, db_index=True, default=8, verbose_name='size_y'),
        ),
    ]
