# Generated by Django 2.2 on 2020-06-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20200626_1218'),
        ('room', '0009_auto_20200628_1831'),
    ]

    operations = [
    ]
